# Generated by Django 5.2.7 on 2025-10-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onlineteam",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="onlineteam",
            name="payment_completed_at",
        ),
        migrations.RemoveField(
            model_name="onlineteam",
            name="payment_completed_by",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="payment_completed_at",
        ),
    ]
