# Generated by Django 5.2.7 on 2025-10-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_discountcode_purchasingitem_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.discountcode",
            ),
        ),
    ]
