# Generated by Django 5.2.7 on 2025-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_username"),
        ("payments", "0003_alter_transaction_ref_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPurchasesSummary",
            fields=[],
            options={
                "verbose_name": "User Purchases Summary",
                "verbose_name_plural": "Users Purchases Summary",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
        migrations.AlterField(
            model_name="purchasingitem",
            name="color",
            field=models.CharField(
                choices=[
                    ("#10b981", "🟢 Green"),
                    ("#3b82f6", "🔵 Blue"),
                    ("#f59e0b", "🟠 Orange"),
                    ("#ef4444", "🔴 Red"),
                    ("#8b5cf6", "🟣 Purple"),
                    ("#ec4899", "🩷 Pink"),
                    ("#14b8a6", "🩵 Teal"),
                    ("#6b7280", "⚫ Gray"),
                ],
                default="#6b7280",
                help_text="Select a color for admin display",
                max_length=7,
            ),
        ),
    ]
