# Generated by Django 5.2.7 on 2025-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_userpurchasessummary_alter_purchasingitem_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
