# Generated by Django 5.2.7 on 2025-10-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcementfilter",
            name="callable_path",
        ),
        migrations.RemoveField(
            model_name="announcementfilter",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="announcementfilter",
            name="name",
        ),
        migrations.RemoveField(
            model_name="announcementfilter",
            name="params",
        ),
    ]
