# Generated by Django 5.2.7 on 2025-10-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0002_remove_announcementfilter_callable_path_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnnouncementFilter",
        ),
    ]
