# Generated by Django 5.2.7 on 2025-11-13 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0003_delete_announcementfilter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userannouncement",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="userannouncement",
            name="email_delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userannouncement",
            name="email_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userannouncement",
            name="email_send_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userannouncement",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="userannouncement",
            unique_together={("announcement", "user")},
        ),
    ]
