# Generated by Django 5.2.7 on 2025-10-27 09:32
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0004_userpurchasessummary_alter_purchasingitem_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LobbygameResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_uuid", models.CharField(max_length=64, unique=True, verbose_name="Request UUID")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
            ],
            options={
                "verbose_name": "Lobby Game Result",
                "verbose_name_plural": "Lobby Game Results",
                "ordering": ["-created_at"],
            },
        ),
    ]
