# Generated by Django 5.2.7 on 2025-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LobbygameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "request_uuid",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Request UUID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("discount_percentage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
            ],
            options={
                "verbose_name": "Lobby Game Result",
                "verbose_name_plural": "Lobby Game Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LobbyGameStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_uuid", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
