# Generated by Django 5.2.7 on 2025-11-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobbygame", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LobbyGameStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_uuid", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="lobbygameresult",
            name="request_uuid",
            field=models.CharField(
                blank=True, max_length=64, null=True, unique=True, verbose_name="Request UUID"
            ),
        ),
    ]
