# Generated by Django 5.2.7 on 2025-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_datetime", models.DateTimeField()),
                ("duration", models.PositiveIntegerField()),
                ("presenter", models.CharField(blank=True, max_length=255, null=True)),
                ("presenter_image", models.URLField(blank=True, null=True)),
                ("vc_link", models.URLField(blank=True)),
                ("place", models.CharField(blank=True, max_length=255)),
                ("record_link", models.URLField(blank=True)),
            ],
        ),
    ]
