# Generated by Django 5.2.7 on 2025-10-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InPersonCompetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phase_0_active",
                    models.BooleanField(default=False, verbose_name="Phase 0 Active"),
                ),
                ("phase_0_title", models.CharField(default="فاز ۰: آشنایی", max_length=200)),
                ("phase_0_description", models.TextField(blank=True)),
                ("phase_0_start", models.DateTimeField(blank=True, null=True)),
                ("phase_0_end", models.DateTimeField(blank=True, null=True)),
                (
                    "phase_1_active",
                    models.BooleanField(default=False, verbose_name="Phase 1 Active"),
                ),
                (
                    "phase_1_title",
                    models.CharField(default="فاز ۱: ایده\u200cپردازی", max_length=200),
                ),
                ("phase_1_description", models.TextField(blank=True)),
                ("phase_1_start", models.DateTimeField(blank=True, null=True)),
                ("phase_1_end", models.DateTimeField(blank=True, null=True)),
                (
                    "phase_2_active",
                    models.BooleanField(default=False, verbose_name="Phase 2 Active"),
                ),
                (
                    "phase_2_title",
                    models.CharField(default="فاز ۲: پیاده\u200cسازی", max_length=200),
                ),
                ("phase_2_description", models.TextField(blank=True)),
                ("phase_2_start", models.DateTimeField(blank=True, null=True)),
                ("phase_2_end", models.DateTimeField(blank=True, null=True)),
                (
                    "phase_3_active",
                    models.BooleanField(default=False, verbose_name="Phase 3 Active"),
                ),
                ("phase_3_title", models.CharField(default="فاز ۳: زیباسازی", max_length=200)),
                ("phase_3_description", models.TextField(blank=True)),
                ("phase_3_start", models.DateTimeField(blank=True, null=True)),
                ("phase_3_end", models.DateTimeField(blank=True, null=True)),
                (
                    "phase_4_active",
                    models.BooleanField(default=False, verbose_name="Phase 4 Active"),
                ),
                ("phase_4_title", models.CharField(default="فاز ۴: نبرد پایانی", max_length=200)),
                ("phase_4_description", models.TextField(blank=True)),
                ("phase_4_start", models.DateTimeField(blank=True, null=True)),
                ("phase_4_end", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "In-Person Competition Settings",
                "verbose_name_plural": "In-Person Competition Settings",
            },
        ),
        migrations.CreateModel(
            name="InPersonTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "avatar",
                    models.TextField(
                        blank=True, help_text="Base64 data URI for team avatar (max 256x256)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("active", "Active"),
                            ("attended", "Attended"),
                            ("disbanded", "Disbanded"),
                        ],
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                ("invite_code", models.CharField(editable=False, max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_inperson_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "In-Person Team",
                "verbose_name_plural": "In-Person Teams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InPersonMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("has_paid", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inperson_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="inperson.inpersonteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "In-Person Team Member",
                "verbose_name_plural": "In-Person Team Members",
                "ordering": ["joined_at"],
                "unique_together": {("team", "user")},
            },
        ),
    ]
