# Generated by Django 5.2.7 on 2025-10-25 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inperson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InPersonSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phase",
                    models.IntegerField(
                        choices=[
                            (0, "Phase 0: Introduction"),
                            (1, "Phase 1: Ideation"),
                            (2, "Phase 2: Development"),
                            (3, "Phase 3: Polish"),
                            (4, "Phase 4: Final Battle"),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="inperson/submissions/"),
                ),
                ("game_url", models.URLField(blank=True)),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("judge_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="inperson.inpersonteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "In-Person Submission",
                "verbose_name_plural": "In-Person Submissions",
                "ordering": ["team", "phase"],
                "unique_together": {("team", "phase")},
            },
        ),
    ]
