# Generated by Django 5.2.7 on 2025-10-29 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inperson", "0002_inpersonsubmission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inpersonsubmission",
            name="description",
        ),
        migrations.RemoveField(
            model_name="inpersonsubmission",
            name="file",
        ),
        migrations.RemoveField(
            model_name="inpersonsubmission",
            name="game_url",
        ),
        migrations.RemoveField(
            model_name="inpersonsubmission",
            name="title",
        ),
        migrations.AddField(
            model_name="inpersonsubmission",
            name="content",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inpersonsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inperson_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inpersonsubmission",
            name="phase",
            field=models.IntegerField(
                choices=[
                    (0, "Phase 0: Introduction"),
                    (2, "Phase 2: Development"),
                    (3, "Phase 3: Polish"),
                    (4, "Phase 4: Final Battle"),
                ]
            ),
        ),
    ]
