# Generated by Django 5.2.7 on 2025-10-29 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inperson", "0003_remove_inpersonsubmission_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inpersonsubmission",
            options={
                "ordering": ["team", "phase", "-submitted_at"],
                "verbose_name": "In-Person Submission",
                "verbose_name_plural": "In-Person Submissions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="inpersonsubmission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="inpersonsubmission",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="inpersonsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_final", True)),
                fields=("team", "phase"),
                name="unique_final_per_team_phase",
            ),
        ),
    ]
