# Generated by Django 5.2.7 on 2025-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inperson", "0004_alter_inpersonsubmission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inpersonteam",
            name="team_number",
            field=models.CharField(
                blank=True,
                help_text="Unique team number for identification",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
