# Generated by Django 5.2.7 on 2025-10-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inperson', '0005_inpersonteam_team_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersonteam',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inpersonteam',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InPersonSolveMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=64, unique=True)),
                ('game_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_hash', to='inperson.inpersonteam')),
                ('game_solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_hash', to='inperson.inpersonteam')),
            ],
        ),
    ]
