# Generated by Django 5.2.7 on 2025-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inperson", "0005_inpersonteam_team_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="inpersonteam",
            name="solve_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inpersonteam",
            name="solved_count",
            field=models.IntegerField(default=0),
        ),
    ]
