# Generated by Django 5.2.7 on 2025-10-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inperson", "0006_inpersonteam_solve_count_inpersonteam_solved_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="inpersonsubmission",
            name="owner_team_number",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name="inpersonsubmission",
            name="solver_team_number",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
