# Generated by Django 5.2.7 on 2025-10-27 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0004_userpurchasessummary_alter_purchasingitem_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MinigameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "carrot_count",
                    models.PositiveIntegerField(default=0, verbose_name="Carrot Count"),
                ),
                ("coin_count", models.PositiveIntegerField(default=0, verbose_name="Coin Count")),
                ("discount_percentage", models.IntegerField(verbose_name="Discount Percentage")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "coupon_code",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minigame_result",
                        to="payments.discountcode",
                        verbose_name="Coupon Code",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minigame_result",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Minigame Result",
                "verbose_name_plural": "Minigame Results",
                "ordering": ["-created_at"],
            },
        ),
    ]
