# Generated by Django 5.2.7 on 2025-10-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Code Updated At"),
        ),
        migrations.AddField(
            model_name="user",
            name="try_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Verification Try Count"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Verification Code"
            ),
        ),
    ]
