# Generated by Django 5.2.7 on 2025-10-17 16:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_code_updated_at_user_try_count_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="has_paid",
            field=models.BooleanField(default=False, verbose_name="Has Paid"),
        ),
        migrations.AddField(
            model_name="user",
            name="normalized_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Normalized Email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_completed",
            field=models.BooleanField(default=False, verbose_name="Profile Completed"),
        ),
        migrations.AlterField(
            model_name="user",
            name="code_updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Code Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name="Verification Code",
            ),
        ),
    ]
