# Generated by Django 5.2.7 on 2025-10-20 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers_user_has_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="National code must be exactly 10 digits", regex="^\\d{10}$"
                    )
                ],
                verbose_name="National Code",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 09 and be 11 digits",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
