# Generated by Django 5.2.7 on 2025-10-26 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code_updated_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Code Updated At",
            ),
        ),
    ]
