# Generated by Django 5.2.7 on 2025-10-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamejam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineCompetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phase_active",
                    models.BooleanField(default=False, verbose_name="Online Phase Active"),
                ),
                ("title", models.CharField(blank=True, default="Online Phase", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Online Competition Settings",
                "verbose_name_plural": "Online Competition Settings",
            },
        ),
        migrations.CreateModel(
            name="OnlineSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="online/submissions/")),
                ("game_url", models.URLField(blank=True)),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("judge_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="gamejam.onlineteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Online Submission",
                "verbose_name_plural": "Online Submissions",
                "ordering": ["team"],
                "unique_together": {("team",)},
            },
        ),
    ]
