# Generated by Django 5.2.7 on 2025-10-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamejam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineteam",
            name="avatar",
            field=models.TextField(
                blank=True, help_text="Base64 data URI for team avatar (max 256x256)"
            ),
        ),
    ]
