# Generated by Django 5.2.7 on 2025-10-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamejam", "0002_onlineteam_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onlinesubmission",
            options={
                "ordering": ["team", "phase", "-submitted_at"],
                "verbose_name": "Online Submission",
                "verbose_name_plural": "Online Submissions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="onlinesubmission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="onlinesubmission",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onlinesubmission",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onlinesubmission",
            name="phase",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="onlinesubmission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="onlinesubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_final", True)),
                fields=("team", "phase"),
                name="unique_final_per_online_team_phase",
            ),
        ),
        migrations.RemoveField(
            model_name="onlinesubmission",
            name="description",
        ),
        migrations.RemoveField(
            model_name="onlinesubmission",
            name="file",
        ),
        migrations.RemoveField(
            model_name="onlinesubmission",
            name="game_url",
        ),
        migrations.RemoveField(
            model_name="onlinesubmission",
            name="title",
        ),
    ]
