# Generated by Django 5.2.7 on 2025-11-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamejam", "0003_alter_onlinesubmission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineteam",
            name="team_number",
            field=models.CharField(
                blank=True,
                help_text="Unique team number for identification",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
